#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Aug 22 14:18:49 HKT 2026
maven-metadata-opencollab-snapshot.xml.lastUpdated=1787379529797
maven-metadata-papermc-repo.xml.error=
maven-metadata-papermc-repo.xml.lastUpdated=1787379529795
maven-metadata-placeholderapi.xml.error=
maven-metadata-placeholderapi.xml.lastUpdated=1787379529794
maven-metadata-sonatype.xml.error=
maven-metadata-sonatype.xml.lastUpdated=1787379529796
