#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Aug 23 19:04:53 HKT 2026
maven-metadata-opencollab-snapshot.xml.lastUpdated=1787483093600
maven-metadata-papermc-repo.xml.error=
maven-metadata-papermc-repo.xml.lastUpdated=1787483093598
maven-metadata-placeholderapi.xml.error=
maven-metadata-placeholderapi.xml.lastUpdated=1787483093596
maven-metadata-sonatype.xml.error=
maven-metadata-sonatype.xml.lastUpdated=1787483093599
