name: HunterGame
version: '9.0v'
main: com.huntergame.HunterGame
api-version: '1.20'
author: YourName
description: A Minecraft Hunter Game plugin.
depend:
  - PlaceholderAPI
softdepend:
  - BaseAPI
libraries:
  - com.zaxxer:HikariCP:5.0.1
commands:
  huntergame:
    description: "HunterGame 插件指令"
    permission: "huntergame.help"
    usage: ""
  hg:
    description: "HunterGame 缩写指令"
    permission: "huntergame.help"
    usage: ""
    subcommands:
      setlobby:
        description: "Set the lobby location."
        permission: "huntergame.setlobby"  # 可选：为子命令设置权限
      startgame:
        description: "Start the Hunter Game."
        permission: "huntergame.startgame"  # 可选：为子命令设置权限
      reload:
        description: "Reload the HunterGame plugin."
        usage: "/huntergame reload"
        permission: "huntergame.reload"
      help:
        description: "Reload the HunterGame plugin."
        usage: "/huntergame help"
        permission: "huntergame.help"


permissions:
  huntergame.help:
    description: "允许玩家查看 HunterGame 帮助"
    default: true
  huntergame.setlobby:
    description: "允许玩家设置 HunterGame 大厅"
    default: op
  huntergame.startgame:
    description: "允许玩家强制开始 HunterGame"
    default: op
  huntergame.reload:
    description: "允许玩家重载 HunterGame 配置"
    default: op
  huntergame.newseason:
    description: "允许玩家开启新赛季"
    default: op
  huntergame.refreshtier:
    description: "允许玩家刷新全服排名"
    default: op
  huntergame.saveprofession:
    description: "允许玩家保存终章职业配置"
    default: op
  huntergame.editprofession:
    description: "允许玩家编辑终章职业物品"
    default: op
