#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Aug 22 14:18:51 HKT 2026
maven-metadata-opencollab-snapshot.xml.error=
maven-metadata-opencollab-snapshot.xml.lastUpdated=1787379531384
maven-metadata-papermc-repo.xml.lastUpdated=1787379531380
maven-metadata-placeholderapi.xml.error=
maven-metadata-placeholderapi.xml.lastUpdated=1787379531378
maven-metadata-sonatype.xml.error=
maven-metadata-sonatype.xml.lastUpdated=1787379531383
